"""Rev

Revision ID: 70bb39799c68
Revises: d54320092157
Create Date: 2023-01-07 03:28:46.873856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bb39799c68'
down_revision = 'd54320092157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_promo_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_valid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_promo_code', schema=None) as batch_op:
        batch_op.drop_column('is_valid')

    # ### end Alembic commands ###
